### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by simon2k13** [Peppershade/uptimekuma-migrator#3]
root@uptimesev:~/uptimekuma-migrator# python3 migrator.py 
Fetching monitors from UptimeRobot API.
Fetched 50 monitors from UptimeRobot API.
Fetching monitors from UptimeRobot API with offset 50.
Fetched 82 monitors from UptimeRobot API.
Syncing monitors to Uptime Kuma API.
Traceback (most recent call last):
  File "/root/uptimekuma-migrator/migrator.py", line 193, in <module>
    sync_monitor_to_uptimekuma(monitor)
  File "/root/uptimekuma-migrator/migrator.py", line 116, in sync_monitor_to_uptimekuma
    api.add_monitor(
  File "/usr/local/lib/python3.10/dist-packages/uptime_kuma_api/api.py", line 1169, in add_monitor
    data = self._build_monitor_data(**kwargs)
TypeError: UptimeKumaApi._build_monitor_data() got an unexpected keyword argument 'expireNotification'

**Comment by Peppershade** [comment]
Should be fixed now, can you try again?

**Comment by simon2k13** [comment]
Works perfect now, but once done script does not exit by itself. Thanks again!

**Comment by Peppershade** [comment]
I added the quit() so it should exit now :)
